/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UserToolsRouteImport } from './routes/user.tools'
import { Route as UserProfileRouteImport } from './routes/user.profile'
import { Route as UserMeetingsRouteImport } from './routes/user.meetings'
import { Route as UserMasterclassesRouteImport } from './routes/user.masterclasses'
import { Route as UserFeedbackRouteImport } from './routes/user.feedback'
import { Route as UserContentRouteImport } from './routes/user.content'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminToolsRouteImport } from './routes/admin.tools'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminMeetingsRouteImport } from './routes/admin.meetings'
import { Route as AdminMasterclassesRouteImport } from './routes/admin.masterclasses'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminContentRouteImport } from './routes/admin.content'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UserToolsRoute = UserToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => UserRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserMeetingsRoute = UserMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => UserRoute,
} as any)
const UserMasterclassesRoute = UserMasterclassesRouteImport.update({
  id: '/masterclasses',
  path: '/masterclasses',
  getParentRoute: () => UserRoute,
} as any)
const UserFeedbackRoute = UserFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => UserRoute,
} as any)
const UserContentRoute = UserContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => UserRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToolsRoute = AdminToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMeetingsRoute = AdminMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMasterclassesRoute = AdminMasterclassesRouteImport.update({
  id: '/masterclasses',
  path: '/masterclasses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/user': typeof UserRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/masterclasses': typeof AdminMasterclassesRoute
  '/admin/meetings': typeof AdminMeetingsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/tools': typeof AdminToolsRoute
  '/admin/users': typeof AdminUsersRoute
  '/user/content': typeof UserContentRoute
  '/user/feedback': typeof UserFeedbackRoute
  '/user/masterclasses': typeof UserMasterclassesRoute
  '/user/meetings': typeof UserMeetingsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/tools': typeof UserToolsRoute
  '/admin/': typeof AdminIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/masterclasses': typeof AdminMasterclassesRoute
  '/admin/meetings': typeof AdminMeetingsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/tools': typeof AdminToolsRoute
  '/admin/users': typeof AdminUsersRoute
  '/user/content': typeof UserContentRoute
  '/user/feedback': typeof UserFeedbackRoute
  '/user/masterclasses': typeof UserMasterclassesRoute
  '/user/meetings': typeof UserMeetingsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/tools': typeof UserToolsRoute
  '/admin': typeof AdminIndexRoute
  '/user': typeof UserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/user': typeof UserRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/masterclasses': typeof AdminMasterclassesRoute
  '/admin/meetings': typeof AdminMeetingsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/tools': typeof AdminToolsRoute
  '/admin/users': typeof AdminUsersRoute
  '/user/content': typeof UserContentRoute
  '/user/feedback': typeof UserFeedbackRoute
  '/user/masterclasses': typeof UserMasterclassesRoute
  '/user/meetings': typeof UserMeetingsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/tools': typeof UserToolsRoute
  '/admin/': typeof AdminIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/user'
    | '/admin/content'
    | '/admin/feedback'
    | '/admin/masterclasses'
    | '/admin/meetings'
    | '/admin/profile'
    | '/admin/tools'
    | '/admin/users'
    | '/user/content'
    | '/user/feedback'
    | '/user/masterclasses'
    | '/user/meetings'
    | '/user/profile'
    | '/user/tools'
    | '/admin/'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/content'
    | '/admin/feedback'
    | '/admin/masterclasses'
    | '/admin/meetings'
    | '/admin/profile'
    | '/admin/tools'
    | '/admin/users'
    | '/user/content'
    | '/user/feedback'
    | '/user/masterclasses'
    | '/user/meetings'
    | '/user/profile'
    | '/user/tools'
    | '/admin'
    | '/user'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/user'
    | '/admin/content'
    | '/admin/feedback'
    | '/admin/masterclasses'
    | '/admin/meetings'
    | '/admin/profile'
    | '/admin/tools'
    | '/admin/users'
    | '/user/content'
    | '/user/feedback'
    | '/user/masterclasses'
    | '/user/meetings'
    | '/user/profile'
    | '/user/tools'
    | '/admin/'
    | '/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/tools': {
      id: '/user/tools'
      path: '/tools'
      fullPath: '/user/tools'
      preLoaderRoute: typeof UserToolsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/meetings': {
      id: '/user/meetings'
      path: '/meetings'
      fullPath: '/user/meetings'
      preLoaderRoute: typeof UserMeetingsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/masterclasses': {
      id: '/user/masterclasses'
      path: '/masterclasses'
      fullPath: '/user/masterclasses'
      preLoaderRoute: typeof UserMasterclassesRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/feedback': {
      id: '/user/feedback'
      path: '/feedback'
      fullPath: '/user/feedback'
      preLoaderRoute: typeof UserFeedbackRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/content': {
      id: '/user/content'
      path: '/content'
      fullPath: '/user/content'
      preLoaderRoute: typeof UserContentRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tools': {
      id: '/admin/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AdminToolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/meetings': {
      id: '/admin/meetings'
      path: '/meetings'
      fullPath: '/admin/meetings'
      preLoaderRoute: typeof AdminMeetingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/masterclasses': {
      id: '/admin/masterclasses'
      path: '/masterclasses'
      fullPath: '/admin/masterclasses'
      preLoaderRoute: typeof AdminMasterclassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminMasterclassesRoute: typeof AdminMasterclassesRoute
  AdminMeetingsRoute: typeof AdminMeetingsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminToolsRoute: typeof AdminToolsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminMasterclassesRoute: AdminMasterclassesRoute,
  AdminMeetingsRoute: AdminMeetingsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminToolsRoute: AdminToolsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface UserRouteChildren {
  UserContentRoute: typeof UserContentRoute
  UserFeedbackRoute: typeof UserFeedbackRoute
  UserMasterclassesRoute: typeof UserMasterclassesRoute
  UserMeetingsRoute: typeof UserMeetingsRoute
  UserProfileRoute: typeof UserProfileRoute
  UserToolsRoute: typeof UserToolsRoute
  UserIndexRoute: typeof UserIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserContentRoute: UserContentRoute,
  UserFeedbackRoute: UserFeedbackRoute,
  UserMasterclassesRoute: UserMasterclassesRoute,
  UserMeetingsRoute: UserMeetingsRoute,
  UserProfileRoute: UserProfileRoute,
  UserToolsRoute: UserToolsRoute,
  UserIndexRoute: UserIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
